server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  sql:
    init:
      platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5433/feedback_intern
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: false
  mail:
    host: smtp.gmail.com
    username: my.application.test.email@gmail.com
    password:
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

